services:
  backend:
    build: ./backend
    container_name: mtbi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mtbi_user:mtbi_password@db:5432/mtbi_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: mtbi-frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: python app.py

  db:
    image: postgres:15
    container_name: mtbi-postgres
    environment:
      - POSTGRES_DB=mtbi_db
      - POSTGRES_USER=mtbi_user
      - POSTGRES_PASSWORD=mtbi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mtbi_user -d mtbi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: