'''add openai api key to users table

Revision ID: 003_add_openai_api_key
Revises: 002_add_test_result_id
Create Date: 2025-09-29 14:00:00.000000

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_add_openai_api_key'
down_revision: Union[str, None] = '002_add_test_result_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openai_api_key')
    # ### end Alembic commands ###
